services:
    php-apache-environment:
        container_name: php-apache-test-BDD
        restart: always
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mysql_db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
        
    mysql_db:
        container_name: mysql_db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"

    phpmyadmin:
        image: phpmyadmin
        ports:
            - '8008:80'
        restart: always
        environment:
            PMA_HOST: mysql_db
        depends_on:
            - mysql_db